apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    age-du-capitaine: quarantedeux
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports: 
    - port: 80
  #ports: 
  #  - name: http
  #    port: 8080
  #    protocol: TCP
  #    targetPort: 80