apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
    age-du-capitaine: quarantedeux
spec:
  containers:
    - name: nginx-app
      image: nginx:latest
      ports:
        - containerPort: 80