apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
#  namespace: api
  labels:
    app: apache
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache-app
          image: httpd:2.4.51-alpine
          ports:
            - containerPort: 80
    
---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
  labels:
    app: apache
spec:
  type: ClusterIP
  selector:
    app: apache
  ports: 
    - port: 80